/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef coordinator_CONSTANTS_H
#define coordinator_CONSTANTS_H

#include "coordinator/coordinator_types.h"

namespace datastore {

class coordinatorConstants {
 public:
  coordinatorConstants();

};

extern const coordinatorConstants g_coordinator_constants;

} // namespace

#endif
