/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "server/dialog_constants.h"

namespace dialog {

const dialogConstants g_dialog_constants;

dialogConstants::dialogConstants() {
}

} // namespace

