/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "rpc_constants.h"

namespace confluo { namespace rpc {

const rpcConstants g_rpc_constants;

rpcConstants::rpcConstants() {
}

}} // namespace

