/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "coordinator/coordinator_constants.h"

namespace datastore {

const coordinatorConstants g_coordinator_constants;

coordinatorConstants::coordinatorConstants() {
}

} // namespace

