/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package confluo.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)")
public class rpc_table_info implements org.apache.thrift.TBase<rpc_table_info, rpc_table_info._Fields>, java.io.Serializable, Cloneable, Comparable<rpc_table_info> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("rpc_table_info");

  private static final org.apache.thrift.protocol.TField TABLE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("table_id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SCHEMA_FIELD_DESC = new org.apache.thrift.protocol.TField("schema", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new rpc_table_infoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new rpc_table_infoTupleSchemeFactory();

  private long table_id; // required
  private java.util.List<rpc_column> schema; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TABLE_ID((short)1, "table_id"),
    SCHEMA((short)2, "schema");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TABLE_ID
          return TABLE_ID;
        case 2: // SCHEMA
          return SCHEMA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TABLE_ID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TABLE_ID, new org.apache.thrift.meta_data.FieldMetaData("table_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SCHEMA, new org.apache.thrift.meta_data.FieldMetaData("schema", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.LIST        , "rpc_schema")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(rpc_table_info.class, metaDataMap);
  }

  public rpc_table_info() {
  }

  public rpc_table_info(
    long table_id,
    java.util.List<rpc_column> schema)
  {
    this();
    this.table_id = table_id;
    set_table_id_isSet(true);
    this.schema = schema;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public rpc_table_info(rpc_table_info other) {
    __isset_bitfield = other.__isset_bitfield;
    this.table_id = other.table_id;
    if (other.is_set_schema()) {
      java.util.List<rpc_column> __this__schema = new java.util.ArrayList<rpc_column>(other.schema.size());
      for (rpc_column other_element : other.schema) {
        __this__schema.add(new rpc_column(other_element));
      }
      this.schema = __this__schema;
    }
  }

  public rpc_table_info deepCopy() {
    return new rpc_table_info(this);
  }

  @Override
  public void clear() {
    set_table_id_isSet(false);
    this.table_id = 0;
    if (this.schema != null) {
      this.schema.clear();
    }
  }

  public long get_table_id() {
    return this.table_id;
  }

  public rpc_table_info set_table_id(long table_id) {
    this.table_id = table_id;
    set_table_id_isSet(true);
    return this;
  }

  public void unset_table_id() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TABLE_ID_ISSET_ID);
  }

  /** Returns true if field table_id is set (has been assigned a value) and false otherwise */
  public boolean is_set_table_id() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TABLE_ID_ISSET_ID);
  }

  public void set_table_id_isSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TABLE_ID_ISSET_ID, value);
  }

  public int get_schema_size() {
    return (this.schema == null) ? 0 : this.schema.size();
  }

  public java.util.Iterator<rpc_column> get_schema_iterator() {
    return (this.schema == null) ? null : this.schema.iterator();
  }

  public void add_to_schema(rpc_column elem) {
    if (this.schema == null) {
      this.schema = new java.util.ArrayList<rpc_column>();
    }
    this.schema.add(elem);
  }

  public java.util.List<rpc_column> get_schema() {
    return this.schema;
  }

  public rpc_table_info set_schema(java.util.List<rpc_column> schema) {
    this.schema = schema;
    return this;
  }

  public void unset_schema() {
    this.schema = null;
  }

  /** Returns true if field schema is set (has been assigned a value) and false otherwise */
  public boolean is_set_schema() {
    return this.schema != null;
  }

  public void set_schema_isSet(boolean value) {
    if (!value) {
      this.schema = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case TABLE_ID:
      if (value == null) {
        unset_table_id();
      } else {
        set_table_id((java.lang.Long)value);
      }
      break;

    case SCHEMA:
      if (value == null) {
        unset_schema();
      } else {
        set_schema((java.util.List<rpc_column>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TABLE_ID:
      return get_table_id();

    case SCHEMA:
      return get_schema();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TABLE_ID:
      return is_set_table_id();
    case SCHEMA:
      return is_set_schema();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof rpc_table_info)
      return this.equals((rpc_table_info)that);
    return false;
  }

  public boolean equals(rpc_table_info that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_table_id = true;
    boolean that_present_table_id = true;
    if (this_present_table_id || that_present_table_id) {
      if (!(this_present_table_id && that_present_table_id))
        return false;
      if (this.table_id != that.table_id)
        return false;
    }

    boolean this_present_schema = true && this.is_set_schema();
    boolean that_present_schema = true && that.is_set_schema();
    if (this_present_schema || that_present_schema) {
      if (!(this_present_schema && that_present_schema))
        return false;
      if (!this.schema.equals(that.schema))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(table_id);

    hashCode = hashCode * 8191 + ((is_set_schema()) ? 131071 : 524287);
    if (is_set_schema())
      hashCode = hashCode * 8191 + schema.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(rpc_table_info other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(is_set_table_id()).compareTo(other.is_set_table_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_table_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.table_id, other.table_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(is_set_schema()).compareTo(other.is_set_schema());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_schema()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.schema, other.schema);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("rpc_table_info(");
    boolean first = true;

    sb.append("table_id:");
    sb.append(this.table_id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("schema:");
    if (this.schema == null) {
      sb.append("null");
    } else {
      sb.append(this.schema);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class rpc_table_infoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public rpc_table_infoStandardScheme getScheme() {
      return new rpc_table_infoStandardScheme();
    }
  }

  private static class rpc_table_infoStandardScheme extends org.apache.thrift.scheme.StandardScheme<rpc_table_info> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, rpc_table_info struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TABLE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.table_id = iprot.readI64();
              struct.set_table_id_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SCHEMA
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                if (struct.schema == null) {
                  struct.schema = new java.util.ArrayList<rpc_column>(_list8.size);
                }
                rpc_column _elem9 = new rpc_column();
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  if (_elem9 == null) {
                    _elem9 = new rpc_column();
                  }
                  _elem9.read(iprot);
                  struct.schema.add(_elem9);
                  _elem9 = null;
                }
                iprot.readListEnd();
              }
              struct.set_schema_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, rpc_table_info struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TABLE_ID_FIELD_DESC);
      oprot.writeI64(struct.table_id);
      oprot.writeFieldEnd();
      if (struct.schema != null) {
        oprot.writeFieldBegin(SCHEMA_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.schema.size()));
          for (rpc_column _iter11 : struct.schema)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class rpc_table_infoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public rpc_table_infoTupleScheme getScheme() {
      return new rpc_table_infoTupleScheme();
    }
  }

  private static class rpc_table_infoTupleScheme extends org.apache.thrift.scheme.TupleScheme<rpc_table_info> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, rpc_table_info struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.is_set_table_id()) {
        optionals.set(0);
      }
      if (struct.is_set_schema()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.is_set_table_id()) {
        oprot.writeI64(struct.table_id);
      }
      if (struct.is_set_schema()) {
        {
          oprot.writeI32(struct.schema.size());
          for (rpc_column _iter12 : struct.schema)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, rpc_table_info struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.table_id = iprot.readI64();
        struct.set_table_id_isSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          if (struct.schema == null) {
            struct.schema = new java.util.ArrayList<rpc_column>(_list13.size);
          }
          rpc_column _elem14 = new rpc_column();
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            if (_elem14 == null) {
              _elem14 = new rpc_column();
            }
            _elem14.read(iprot);
            struct.schema.add(_elem14);
            _elem14 = null;
          }
        }
        struct.set_schema_isSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

