/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "server_constants.h"

namespace succinct {

const serverConstants g_server_constants;

serverConstants::serverConstants() {
}

} // namespace

