var searchData=
[
  ['record',['Record',['../classconfluo_1_1rpc_1_1_record.html',1,'confluo::rpc']]],
  ['recordbatchbuilder',['RecordBatchBuilder',['../classconfluo_1_1rpc_1_1_record_batch_builder.html',1,'confluo::rpc']]],
  ['recordstream',['RecordStream',['../classconfluo_1_1rpc_1_1_record_stream.html',1,'confluo::rpc']]],
  ['rpc_5fatomic_5fmultilog_5finfo',['rpc_atomic_multilog_info',['../classconfluo_1_1rpc_1_1rpc__atomic__multilog__info.html',1,'confluo::rpc']]],
  ['rpc_5fcolumn',['rpc_column',['../classconfluo_1_1rpc_1_1rpc__column.html',1,'confluo::rpc']]],
  ['rpc_5fdata_5ftype',['rpc_data_type',['../enumconfluo_1_1rpc_1_1rpc__data__type.html',1,'confluo::rpc']]],
  ['rpc_5finvalid_5foperation',['rpc_invalid_operation',['../classconfluo_1_1rpc_1_1rpc__invalid__operation.html',1,'confluo::rpc']]],
  ['rpc_5fiterator_5fdescriptor',['rpc_iterator_descriptor',['../classconfluo_1_1rpc_1_1rpc__iterator__descriptor.html',1,'confluo::rpc']]],
  ['rpc_5fiterator_5fhandle',['rpc_iterator_handle',['../classconfluo_1_1rpc_1_1rpc__iterator__handle.html',1,'confluo::rpc']]],
  ['rpc_5fiterator_5ftype',['rpc_iterator_type',['../enumconfluo_1_1rpc_1_1rpc__iterator__type.html',1,'confluo::rpc']]],
  ['rpc_5fmanagement_5fexception',['rpc_management_exception',['../classconfluo_1_1rpc_1_1rpc__management__exception.html',1,'confluo::rpc']]],
  ['rpc_5frecord_5fbatch',['rpc_record_batch',['../classconfluo_1_1rpc_1_1rpc__record__batch.html',1,'confluo::rpc']]],
  ['rpc_5frecord_5fblock',['rpc_record_block',['../classconfluo_1_1rpc_1_1rpc__record__block.html',1,'confluo::rpc']]],
  ['rpc_5fservice',['rpc_service',['../classconfluo_1_1rpc_1_1rpc__service.html',1,'confluo::rpc']]],
  ['rpc_5fstorage_5fmode',['rpc_storage_mode',['../enumconfluo_1_1rpc_1_1rpc__storage__mode.html',1,'confluo::rpc']]],
  ['rpcclient',['RpcClient',['../classconfluo_1_1rpc_1_1_rpc_client.html',1,'confluo::rpc']]]
];
