/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef log_store_CONSTANTS_H
#define log_store_CONSTANTS_H

#include "server/log_store_types.h"

namespace datastore {

class log_storeConstants {
 public:
  log_storeConstants();

};

extern const log_storeConstants g_log_store_constants;

} // namespace

#endif
